server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/hotel?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.108
    port: 5672
    username: itcast
    password: 123456
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo